language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install flake8
    - pip install coveralls

before_script:
    - flake8 --show-source

script:
    - py.test

after_success:
    - coveralls
